# Generated by Django 2.1.7 on 2019-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='end',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='start',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
