# Generated by Django 2.1.7 on 2019-03-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_auto_20190319_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=200)),
                ('end', models.CharField(default='', max_length=200)),
                ('distance', models.FloatField(default=0)),
                ('employee_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='trip_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip'),
        ),
    ]
