# Generated by Django 2.1.7 on 2019-03-19 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_auto_20190319_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 12, 30, 7, 216589, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
