# Generated by Django 2.1.7 on 2019-03-19 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_tripdetail_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 12, 55, 36, 801247, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
