# Generated by Django 2.1.7 on 2019-03-22 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_auto_20190319_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='employee_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 27, 18, 575076, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
