# Generated by Django 2.1.7 on 2019-03-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0011_auto_20190322_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='evidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trip.Evidence'),
        ),
    ]
