# Generated by Django 2.1.7 on 2019-03-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0013_auto_20190322_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInformation',
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip'),
        ),
    ]
