# Generated by Django 2.1.7 on 2019-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0015_auto_20190322_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='cost',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='project_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
