# Generated by Django 2.1.7 on 2019-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0016_auto_20190326_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='project_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='project_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
