# Generated by Django 2.1.7 on 2019-03-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0017_auto_20190326_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='TripDetail',
        ),
        migrations.AddField(
            model_name='evidence',
            name='Trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip'),
        ),
    ]
