# Generated by Django 2.1.7 on 2019-03-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0018_auto_20190326_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='Trip',
        ),
        migrations.AddField(
            model_name='evidence',
            name='TripDetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.TripDetail'),
        ),
    ]
