# Generated by Django 2.1.7 on 2019-04-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0019_evidence_extra_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='', max_length=200)),
                ('trip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=200)),
                ('trip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip')),
            ],
        ),
    ]
