# Generated by Django 2.1.7 on 2019-03-22 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0007_auto_20190322_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 52, 13, 361021, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
