# Generated by Django 2.1.7 on 2019-03-22 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0008_auto_20190322_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 54, 46, 291652, tzinfo=utc), verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 11, 54, 46, 302652, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
