# Generated by Django 2.1.7 on 2019-03-22 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0009_auto_20190322_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetail',
            old_name='trip_number',
            new_name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_number',
        ),
        migrations.AlterField(
            model_name='trip',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 14, 34, 801185, tzinfo=utc), verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 12, 14, 34, 801185, tzinfo=utc), verbose_name='Trip date'),
        ),
    ]
