# Generated by Django 2.1.7 on 2019-03-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0012_tripdetail_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='evidence',
        ),
        migrations.AddField(
            model_name='evidence',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trip.Trip'),
        ),
    ]
